# Generated by Django 4.2.1 on 2023-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('production_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=255)),
                ('leading_actor', models.CharField(max_length=255)),
                ('day_of_view', models.DateField()),
                ('review_score', models.PositiveIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('streaming_site', models.URLField(blank=True)),
            ],
        ),
    ]
